language: scala
dist: trusty
jdk:
- oraclejdk8
scala:
- 2.11.12
- 2.12.8
sudo: false
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
before_script:
- rm project/pgp.sbt && rm project/sbt-updates.sbt && rm project/sonatype.sbt
- git add . --all
